services:
  - type: web
    name: schoolhub
    env: docker
    plan: free
    autoDeploy: true
    region: frankfurt
    disk:
      name: data
      mountPath: /data
      sizeGB: 5
    envVars:
      - key: DATA_DIR
        value: /data